version: '3.8'

services:
  app-employee-api:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      db-employee:
        condition: service_healthy
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DB_HOST=db-employee
      - DB_PORT=5432
      - DB_NAME=employee_management
      - DB_USER=postgres
      - DB_PASSWORD=P@ssword0123
      - JWT_SECRET=votre_secret_jwt
      - JWT_EXPIRES_IN=24h
    volumes:
      - ./:/app
      - /app/node_modules
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  db-employee:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=P@ssword0123
      - POSTGRES_DB=employee_management
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres_data: