name: Deploy to Minikube

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed

jobs:
  deploy-to-minikube:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get package version
        id: package-version
        run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Set up Minikube
        uses: medyagh/setup-minikube@master
        with:
          minikube-version: 1.30.1
          kubernetes-version: v1.27.3
          driver: docker

      - name: Configure Minikube
        run: |
          minikube addons enable ingress
          minikube status
          kubectl get pods -A

      - name: Create Kubernetes namespace
        run: |
          kubectl create namespace employee-api --dry-run=client -o yaml | kubectl apply -f -

      - name: Create Kubernetes secrets
        run: |
          kubectl create secret generic employee-api-secrets \
            --namespace=employee-api \
            --from-literal=DB_PASSWORD=P@ssword01 \
            --from-literal=JWT_SECRET=votre_secret_jwt \
            --dry-run=client -o yaml | kubectl apply -f -

      - name: Deploy to Kubernetes
        run: |
          # Apply Kubernetes manifests
          kubectl apply -f k8s/

      - name: Wait for deployment
        run: |
          kubectl rollout status deployment/employee-api -n employee-api --timeout=180s

      - name: Get service URL
        run: |
          minikube service employee-api -n employee-api --url
          echo "Application deployed successfully to Minikube"