name: Create Release

on:
  workflow_run:
    workflows: ["Build and Test"]
    branches: [main, master]
    types:
      - completed

jobs:
  create-release:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Get package version
        id: package-version
        run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.package-version.outputs.version }}
          release_name: Release v${{ steps.package-version.outputs.version }}
          draft: false
          prerelease: false
          body: |
            ## Employee Management API Release v${{ steps.package-version.outputs.version }}
            
            ### Changes in this Release
            * Automated release based on successful build and tests
            
            ### Docker Image
            * Image available at: ghcr.io/${{ github.repository }}:v${{ steps.package-version.outputs.version }}